#!/bin/bash

if [ $# -ne 1 ]; then
  echo "cdn: Error: Incorrect number of arguments provided."
  echo "Usage: cdn directory_name"
else
	if [ ! -d $1 ]; then
		mkdir $1 && cd $1 || { echo "Could not create directory"; exit 1; }
	else
		echo "Directory already exists!"
		cd $1
	fi
fi

