#!/bin/bash

if [ $# -ne 1 ]; then
  echo "cdn: Error: Incorrect number of arguments provided."
  echo "Usage: cdn name"
  exit 1
fi

if [ ! -d $1 ]; then
  mkdir $1 && cd $1 || { echo "Could not create directory"; exit 1; }
else
  echo "Directory already exists!"
  cd $1
fi
