#!/bin/bash

# Location of the lock file
LOCK="$HOME/.config/niri/scripts/locker-$WAYLAND_DISPLAY.lock"

# Cleanup function for TERM/INT signals
function graceful_exit {
  rm $LOCK && echo "Inhibition ended" || \
    (echo "Could not end inhibition"; \
     echo "Check for lock file at: $LOCK")
  trap SIGTERM
  trap SIGINT
  exit
}

echo "Inhibiting screen locker..."

# Create the lock file
touch $LOCK || exit

trap "graceful_exit" SIGTERM
trap "graceful_exit" SIGINT

# Wait for user input
echo "Press any key to resume:"
read -s -n 1

# Remove lock file
graceful_exit
